# Generated by Django 4.2.4 on 2023-08-07 12:48

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PatientFirstName', models.CharField(max_length=200)),
                ('PatientLastName', models.CharField(max_length=75)),
                ('PatientAge', models.CharField(blank=True, choices=[('j', 'jours'), ('m', 'Mois'), ('a', 'ans')], default='m', help_text='Selectionner', max_length=1)),
                ('PatientSexe', models.CharField(blank=True, choices=[('m', 'Masculin'), ('f', 'Feminin')], default='m', help_text='Selectionner le genre', max_length=1)),
                ('section', multiselectfield.db.fields.MultiSelectField(choices=[('P', 'Parasitologie'), ('H', 'Hematology'), ('I', 'Immunologie'), ('B', 'Biochimie'), ('M', 'Microbiologie')], max_length=10)),
                ('Examen', multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Goute eppaisse'), ('2', 'PCR'), ('3', 'NFS'), ('4', 'CRP'), ('5', 'Ionnogramme sanguin'), ('6', 'Triglycerides'), ('7', 'Coproculture'), ('8', 'Hemoculture'), ('8', 'Uroculture'), ('8', 'LCS'), ('8', 'Ecouvillonnage'), ('8', 'Liquide ascite')], max_length=10)),
            ],
        ),
    ]
