# Generated by Django 4.2.4 on 2023-08-07 12:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('labapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examen',
            old_name='PatientLastName',
            new_name='Nom_de_famille',
        ),
        migrations.RenameField(
            model_name='examen',
            old_name='PatientFirstName',
            new_name='Prénoms',
        ),
        migrations.AlterField(
            model_name='examen',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular patient across whole library', primary_key=True, serialize=False),
        ),
    ]
