# Generated by Django 4.2.4 on 2023-08-07 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labapp', '0002_rename_patientlastname_examen_nom_de_famille_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examen',
            old_name='Examen',
            new_name='examen',
        ),
        migrations.RenameField(
            model_name='examen',
            old_name='PatientSexe',
            new_name='sexe',
        ),
        migrations.RenameField(
            model_name='examen',
            old_name='PatientAge',
            new_name='temps',
        ),
    ]
