# Generated by Django 4.2.4 on 2023-08-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labapp', '0003_rename_examen_examen_examen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='age',
            field=models.PositiveIntegerField(default='1'),
        ),
    ]
