# Generated by Django 4.2.4 on 2023-08-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labapp', '0004_examen_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='Id_projet',
            field=models.CharField(default='1', help_text='Entrez Id du participant dans le projet', max_length=50),
        ),
        migrations.AddField(
            model_name='examen',
            name='prescipteur',
            field=models.CharField(default='Dr Ouedraogo', max_length=50),
        ),
    ]
