# Generated by Django 4.2.4 on 2023-08-08 09:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labapp', '0005_examen_id_projet_examen_prescipteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='date_et_heure_de_demande',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 8, 9, 37, 49, 731214, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
