# Generated by Django 4.2.4 on 2023-08-08 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labapp', '0006_examen_date_et_heure_de_demande'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examen',
            options={'ordering': ['id']},
        ),
    ]
