# Generated by Django 4.2.4 on 2023-08-08 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labapp', '0007_alter_examen_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examen',
            options={},
        ),
    ]
