# Generated by Django 4.2.4 on 2023-08-08 10:15

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('labapp', '0008_alter_examen_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='age',
            field=models.PositiveIntegerField(default='20'),
        ),
        migrations.AlterField(
            model_name='examen',
            name='examen',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Goute epaisse', 'Goute epaisse'), ('PCR', 'PCR'), ('NFS', 'NFS'), ('CRP', 'CRP'), ('Ionnogramme sanguin', 'Ionnogramme sanguin'), ('Triglycerides', 'Triglycerides'), ('Coproculture', 'Coproculture'), ('Hemoculture', 'Hemoculture'), ('Uroculture', 'Uroculture'), ('LCS', 'LCS'), ('Ecouvillonnage', 'Ecouvillonnage'), ('Liquide ascite', 'Liquide ascite')], max_length=100),
        ),
        migrations.AlterField(
            model_name='examen',
            name='section',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('P', 'Parasitologie'), ('H', 'Hematology'), ('I', 'Immunologie'), ('B', 'Biochimie'), ('M', 'Microbiologie')], max_length=20),
        ),
        migrations.AlterField(
            model_name='examen',
            name='sexe',
            field=models.CharField(blank=True, choices=[('m', 'Masculin'), ('f', 'Feminin')], default='m', help_text='Selectionner le genre', max_length=10),
        ),
        migrations.AlterField(
            model_name='examen',
            name='temps',
            field=models.CharField(blank=True, choices=[('jours', 'jours'), ('Mois', 'Mois'), ('ans', 'ans')], default='m', help_text='Selectionner', max_length=20),
        ),
    ]
