# Generated by Django 4.2.4 on 2023-08-17 15:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('labapp', '0009_alter_examen_age_alter_examen_examen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='Projet',
            field=models.CharField(default='VAC078', max_length=50),
        ),
        migrations.AddField(
            model_name='examen',
            name='renseignements_cliniques',
            field=models.TextField(default='fièvre, vomissement'),
        ),
        migrations.AlterField(
            model_name='examen',
            name='age',
            field=models.PositiveIntegerField(default='2', help_text='Entrer age du patien (en années)'),
        ),
        migrations.AlterField(
            model_name='examen',
            name='id',
            field=models.UUIDField(default=uuid.uuid1, help_text='Unique ID for this particular patient across whole library', primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Archivage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type_echantillon', models.CharField(choices=[('sang', 'sang'), ('Serum', 'Serum'), ('Plasma', 'Plasma'), ('PCR', 'PCR'), ('Lame', 'Lame'), ('LCS', 'LCS'), ('Souche', 'Souche'), ('Autres', 'Autres')], default='sang', help_text='Selectionner le type échantillon à archiver', max_length=10)),
                ('Projet', models.CharField(max_length=50)),
                ('Réfrigérateur', models.CharField(max_length=50)),
                ('Rangée', models.PositiveIntegerField()),
                ('Boite', models.PositiveIntegerField()),
                ('Position', models.PositiveIntegerField()),
                ('Date_et_heure_archivage', models.DateTimeField()),
                ('Id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='labapp.examen')),
            ],
        ),
    ]
