# Generated by Django 4.2.4 on 2023-08-17 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labapp', '0010_examen_projet_examen_renseignements_cliniques_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivage',
            name='Id',
        ),
        migrations.AlterField(
            model_name='archivage',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='labapp.examen'),
        ),
    ]
