# Generated by Django 4.2.4 on 2023-08-19 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labapp', '0012_archivage_auteur_examen_autheur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archivage',
            old_name='Auteur',
            new_name='Autheur',
        ),
        migrations.AddField(
            model_name='archivage',
            name='Etude',
            field=models.CharField(default='A quel etude appartient echantillon?', max_length=100),
        ),
    ]
