# Generated by Django 4.2.4 on 2023-08-19 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labapp', '0014_archivage_id_examen_alter_archivage_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archivage',
            old_name='id',
            new_name='id_projet',
        ),
    ]
