# Generated by Django 4.2.4 on 2023-08-19 23:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('labapp', '0017_alter_archivage_id_projet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivage',
            name='id_projet',
            field=models.OneToOneField(default='NFS', null=True, on_delete=django.db.models.deletion.CASCADE, to='labapp.examen'),
        ),
        migrations.AlterField(
            model_name='examen',
            name='Autheur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
